// Root build: aggregates lifecycle tasks (build/clean) across modules.
// Per-module configuration comes from the convention plugins in build-logic;
// there is intentionally no `allprojects`/`subprojects` block (Gradle anti-pattern).
import groovy.json.JsonSlurper

plugins {
    base
}

// ---------------------------------------------------------------------------
// Generated project manifests — docs/generated/{services,events}.yaml
//
// The machine-readable, drift-checked registry an AI agent (or tooling) can query
// instead of parsing prose. MECHANICAL FACTS ONLY, regenerated from the single
// sources of truth so the docs cannot silently drift:
//   * services.yaml  <-  settings.gradle.kts + services/*/db/migration + build.gradle.kts
//   * events.yaml    <-  libs/contracts/src/main/resources/avro/*.avsc  (ADR 0003)
//
// Producer/consumer relationships are intentionally NOT derived here — they are
// brittle to parse from source and live in docs/EVENT-CATALOG.md (prose).
//
//   ./gradlew generateProjectDocs   regenerate + commit the YAML
//   ./gradlew verifyProjectDocs     fail if the committed YAML is stale, or a schema
//                                   has no EVENT-CATALOG entry (rule 7). Wired into `check`.
// ---------------------------------------------------------------------------

val repoRoot: File = projectDir

fun renderAvroType(t: Any?): String =
    when (t) {
        is String -> t
        is List<*> -> t.joinToString("|") { renderAvroType(it) }
        is Map<*, *> -> {
            val logical = t["logicalType"]
            val type = t["type"]
            when {
                logical != null -> logical.toString()
                type == "array" -> "array<${renderAvroType(t["items"])}>"
                type == "record" -> "record:${t["name"]}"
                type == "enum" -> "enum:${t["name"]}"
                type == "map" -> "map<${renderAvroType(t["values"])}>"
                else -> renderAvroType(type)
            }
        }
        else -> t.toString()
    }

fun avroFiles(root: File): List<File> =
    File(root, "libs/contracts/src/main/resources/avro")
        .listFiles { f -> f.name.endsWith(".avsc") }
        ?.sortedBy { it.name } ?: emptyList()

fun generateManifests(root: File, targetDir: File) {
    targetDir.mkdirs()

    // services.yaml — from settings.gradle.kts + migration filenames + the libs:contracts dep.
    val settingsText = File(root, "settings.gradle.kts").readText()
    val serviceNames =
        Regex("""include\("services:([^"]+)"\)""").findAll(settingsText)
            .map { it.groupValues[1] }.toList().sorted()

    val s = StringBuilder()
    s.append("# GENERATED by ./gradlew generateProjectDocs — DO NOT EDIT BY HAND.\n")
    s.append("# Source: settings.gradle.kts + services/*/src/main/resources/db/migration + build.gradle.kts\n")
    s.append("services:\n")
    for (name in serviceNames) {
        val svcDir = File(root, "services/$name")
        val migs =
            (File(svcDir, "src/main/resources/db/migration")
                    .listFiles { f -> f.name.matches(Regex("""V\d+__.*\.sql""")) } ?: emptyArray())
                .map { Regex("""V(\d+)__""").find(it.name)!!.groupValues[1].toInt() }
                .sorted()
        val buildText = File(svcDir, "build.gradle.kts").takeIf { it.exists() }?.readText() ?: ""
        val hasEvents = buildText.contains("libs:contracts")
        s.append("  - name: $name\n")
        s.append("    module: \":services:$name\"\n")
        s.append(
            if (migs.isEmpty()) "    migrations: { count: 0, range: \"none\" }\n"
            else "    migrations: { count: ${migs.size}, range: \"V${migs.first()}..V${migs.last()}\" }\n")
        s.append("    events: $hasEvents\n")
    }
    File(targetDir, "services.yaml").writeText(s.toString())

    // events.yaml — from the single schema source (libs/contracts).
    val e = StringBuilder()
    e.append("# GENERATED by ./gradlew generateProjectDocs — DO NOT EDIT BY HAND.\n")
    e.append("# Source: libs/contracts/src/main/resources/avro/*.avsc (the single schema source — ADR 0003)\n")
    e.append("# Producer/consumer relationships live in docs/EVENT-CATALOG.md (prose, hand-maintained).\n")
    e.append("events:\n")
    for (avsc in avroFiles(root)) {
        @Suppress("UNCHECKED_CAST")
        val schema = JsonSlurper().parse(avsc) as Map<String, Any?>
        e.append("  - name: ${schema["name"]}\n")
        e.append("    namespace: ${schema["namespace"] ?: ""}\n")
        e.append("    schema: libs/contracts/src/main/resources/avro/${avsc.name}\n")
        val fields = schema["fields"] as? List<*> ?: emptyList<Any?>()
        if (fields.isEmpty()) {
            e.append("    fields: []\n")
        } else {
            e.append("    fields:\n")
            for (f in fields) {
                val fm = f as Map<*, *>
                e.append("      - { name: ${fm["name"]}, type: \"${renderAvroType(fm["type"])}\" }\n")
            }
        }
    }
    File(targetDir, "events.yaml").writeText(e.toString())
}

tasks.register("generateProjectDocs") {
    group = "documentation"
    description = "Regenerate docs/generated/{services,events}.yaml from the single sources of truth."
    val root = repoRoot
    doLast {
        generateManifests(root, File(root, "docs/generated"))
        logger.lifecycle("Generated docs/generated/services.yaml + events.yaml")
    }
}

tasks.register("verifyProjectDocs") {
    group = "verification"
    description =
        "Fail if docs/generated/*.yaml drift from a fresh regeneration, or a schema lacks an EVENT-CATALOG entry."
    val root = repoRoot
    doLast {
        val tmp = File(root, "build/generated-docs-check").apply { deleteRecursively() }
        generateManifests(root, tmp)
        for (fn in listOf("services.yaml", "events.yaml")) {
            val fresh = File(tmp, fn).readText().replace("\r\n", "\n")
            val committed =
                File(root, "docs/generated/$fn").takeIf { it.exists() }?.readText()?.replace("\r\n", "\n")
                    ?: ""
            if (fresh != committed) {
                throw GradleException(
                    "docs/generated/$fn is stale — run ./gradlew generateProjectDocs and commit the result.")
            }
        }
        // Rule 7: every event schema must have an EVENT-CATALOG.md entry.
        val catalog = File(root, "docs/EVENT-CATALOG.md").readText()
        val missing = avroFiles(root).map { it.name.removeSuffix(".avsc") }.filter { !catalog.contains(it) }
        if (missing.isNotEmpty()) {
            throw GradleException("Events missing from docs/EVENT-CATALOG.md (rule 7): $missing")
        }
        logger.lifecycle("Project docs in sync (${avroFiles(root).size} events).")
    }
}

tasks.named("check") { dependsOn("verifyProjectDocs") }
