-- service-template baseline (M0.3).
--
-- One sample table (`widget`) carrying the mandatory Auditable columns
-- (created_at/by, updated_at/by, version, company_id) and a PostgreSQL
-- row-level-security policy keyed to the session tenant. Every Native table
-- follows this exact shape: Auditable columns + an RLS policy on app.current_tenant.
--
-- The application connects as a NON-superuser role (without BYPASSRLS), so the
-- policy is genuinely enforced; the migration owner may be a superuser, which is
-- why FORCE ROW LEVEL SECURITY is set (so even the table owner is subject to the
-- policy and the "forgot WHERE can't leak" guarantee holds end to end).

CREATE TABLE widget (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,

    -- Auditable (libs/tenant) — present on every Native table.
    created_at TIMESTAMPTZ  NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    version    BIGINT       NOT NULL,
    company_id VARCHAR(64)  NOT NULL
);

-- Defense in depth: tenant isolation enforced a second time by the database.
ALTER TABLE widget ENABLE ROW LEVEL SECURITY;
-- FORCE so the policy applies even to the table owner / migration role, not just
-- to other roles — no connection silently bypasses tenant isolation.
ALTER TABLE widget FORCE ROW LEVEL SECURITY;

-- A row is visible/writable only when its company_id equals the session tenant.
-- current_setting(..., true) returns NULL (not an error) when the GUC is unset,
-- so with no tenant bound the predicate is false for every row -> fail closed.
CREATE POLICY widget_tenant_isolation ON widget
    USING (company_id = current_setting('app.current_tenant', true))
    WITH CHECK (company_id = current_setting('app.current_tenant', true));
