package id.co.nativeapp.restaurant.giftcard.domain;

import id.co.nativeapp.money.Money;
import id.co.nativeapp.restaurant.sale.domain.MoneyEmbeddable;
import id.co.nativeapp.tenant.Auditable;
import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * The {@code gift_card_sale} aggregate — this vertical's own record of selling (or later, topping
 * up) a gift card at the till (ADR 0027, Phase 4). NOT a sale of goods/services and NEVER folded
 * into {@link id.co.nativeapp.restaurant.sale.domain.Sale Sale}/{@code SaleRecorded} — a gift-card
 * sale is a LIABILITY event, not revenue (V17 migration comment). Emits {@code GiftCardSold} via
 * the outbox in the SAME transaction (rule 3).
 *
 * <p>{@code giftCardId} carries the UUID minted AT THE TILL at the moment of sale (ADR 0027
 * decision 5) — the human-facing {@link GiftCardCodeGenerator#deriveCode(UUID)} code is a pure
 * function of this id, so it never needs to round-trip through loyalty-service before the receipt
 * can print it.
 *
 * <p>Extends {@link Auditable} (rule 4) and is covered by the {@code gift_card_sale} RLS policy
 * (rule 5). {@code (company_id, idempotency_key)} carries a UNIQUE constraint — producer
 * idempotency, the same contract {@link id.co.nativeapp.restaurant.sale.domain.Sale Sale} follows.
 */
@Entity
@Table(name = "gift_card_sale")
public class GiftCardSale extends Auditable {

  @Id
  @Column(name = "id", nullable = false, updatable = false)
  private UUID id;

  @Column(name = "gift_card_id", nullable = false, updatable = false)
  private UUID giftCardId;

  @Column(name = "business_id", nullable = false, updatable = false)
  private UUID businessId;

  @Embedded
  @AttributeOverrides({
    @AttributeOverride(
        name = "amountMinor",
        column = @Column(name = "amount_minor", nullable = false)),
    @AttributeOverride(
        name = "currency",
        column = @Column(name = "currency", nullable = false, length = 3))
  })
  private MoneyEmbeddable amount;

  @Column(name = "tender_type", length = 16)
  private String tenderType;

  @Column(name = "occurred_at", nullable = false, updatable = false)
  private Instant occurredAt;

  @Column(name = "idempotency_key", nullable = false, updatable = false)
  private String idempotencyKey;

  protected GiftCardSale() {
    // for JPA
  }

  /**
   * Creates a new gift-card sale record.
   *
   * @param giftCardId the card UUID minted at the till (never generated by this entity)
   * @param businessId the outlet the card was sold at
   * @param amount the stored-value amount loaded onto the card (must be positive; enforced by the
   *     DB CHECK, not re-validated here — the writer validates before construction)
   * @param tenderType {@code CASH}/{@code QRIS}/{@code CARD}, or {@code null} for an unspecified
   *     tender
   * @param occurredAt when the sale/top-up occurred
   * @param idempotencyKey the client's request id (dedupe key with company_id)
   */
  public GiftCardSale(
      UUID giftCardId,
      UUID businessId,
      Money amount,
      String tenderType,
      Instant occurredAt,
      String idempotencyKey) {
    this.id = UUID.randomUUID();
    this.giftCardId = Objects.requireNonNull(giftCardId, "giftCardId");
    this.businessId = Objects.requireNonNull(businessId, "businessId");
    this.amount = MoneyEmbeddable.of(Objects.requireNonNull(amount, "amount"));
    this.tenderType = tenderType;
    this.occurredAt = Objects.requireNonNull(occurredAt, "occurredAt");
    this.idempotencyKey = Objects.requireNonNull(idempotencyKey, "idempotencyKey");
  }

  public UUID getId() {
    return id;
  }

  public UUID getGiftCardId() {
    return giftCardId;
  }

  public UUID getBusinessId() {
    return businessId;
  }

  /** The card's loaded value as a {@link Money} value (reconstructed from its columns). */
  public Money getAmount() {
    return amount.toMoney();
  }

  public String getTenderType() {
    return tenderType;
  }

  public Instant getOccurredAt() {
    return occurredAt;
  }

  public String getIdempotencyKey() {
    return idempotencyKey;
  }
}
