#!/usr/bin/env bash
# Native PROD bootstrap — runs ON THE VPS. First bring-up (and quick-tunnel re-wire) of the
# production stack (ADR 0057, Phase 5). The bash port of scripts/uat-up.ps1's wire-up path:
#
#   bash prod-bootstrap.sh <release> [--skip-pull]
#
#   <release>     name of releases/<release>.images.yml (digest-pinned from deploy-prod.yml,
#                 or a hand-written bootstrap manifest for a locally-loaded image set)
#   --skip-pull   don't `compose pull` (images were docker-load'ed onto this host)
#
# What it does, in order:
#   1. secrets    generate prod.env with FRESH values on first run (chmod 600; refuses to run
#                 against an existing data volume without its prod.env — ciphertexts are bound)
#   2. tunnels    start edge + both cloudflared QUICK tunnels, discover the two public URLs
#   3. env        write PUBLIC_URL / EMPLOYEE_PUBLIC_URL into prod.env
#   4. stack      full compose up (first boot pays Flyway + KC realm import + MinIO init)
#   5. keycloak   patch native-console client to the current origins; rotate native-admin
#                 secret; disable native-gateway client + seed users; apply the ADR 0054 realm
#                 hardening (brute force failureFactor=15, password policy) — values mirrored
#                 from the live UAT realm
#   6. debezium   register every docker/debezium/*.json connector (idempotent PUT) + wait RUNNING
#   7. smoke      through the PUBLIC tunnel URLs (env.js, OIDC issuer, 401 API, blackholed admin)
#
# Re-run any time the quick tunnels died/restarted (they mint NEW URLs): it re-discovers, rewrites
# prod.env, recreates the URL-dependent containers and re-patches Keycloak. Idempotent throughout.
# Named-tunnel future: set the stable URLs in prod.env, COMPOSE_PROFILES=namedtunnel, re-run.
set -euo pipefail

DEPLOY_DIR="${NATIVE_PROD_DIR:-$HOME/native-prod}"
RELEASE="${1:?usage: prod-bootstrap.sh <release> [--skip-pull]}"
SKIP_PULL="${2:-}"
cd "$DEPLOY_DIR"
log() { echo "[$(date -u +%FT%TZ)] $*" | tee -a deploy.log; }

command -v jq >/dev/null  || { echo "FATAL: jq required (sudo apt-get install -y jq)"; exit 2; }
command -v curl >/dev/null || { echo "FATAL: curl required"; exit 2; }
MANIFEST="releases/$RELEASE.images.yml"
[ -f "$MANIFEST" ] || { echo "FATAL: $MANIFEST missing"; exit 2; }

exec 9>deploy.lock
flock -n 9 || { log "ABORT: a deploy/rollback/bootstrap already holds the lock"; exit 2; }

# ---- 1. secrets ------------------------------------------------------------------------------
new_secret() { openssl rand -base64 "${1:-32}"; }
if [ ! -f prod.env ]; then
  if docker volume ls --format '{{.Name}}' | grep -q '^native-prod_native-prod-pgdata$'; then
    echo "FATAL: prod.env is MISSING but the native-prod data volume exists. The PII/gift-card"
    echo "ciphertexts and the KC admin password are bound to the lost secrets. Restore prod.env"
    echo "from the encrypted offsite copy, or wipe the volumes deliberately before re-running."
    exit 2
  fi
  log "first run: generating prod.env with fresh secrets (chmod 600)"
  umask 177
  cat > prod.env <<EOF
# GENERATED by prod-bootstrap.sh $(date -u +%F) — NEVER commit; keep an ENCRYPTED offsite copy.
COMPOSE_PROFILES=quicktunnel
IMAGE_BASE=ghcr.io/rfkih/native-monorepo
NATIVE_IMAGE_TAG=bootstrap
PUBLIC_URL=http://localhost
EMPLOYEE_PUBLIC_URL=http://localhost
KC_ADMIN_PASSWORD=$(new_secret 18)
KEYCLOAK_ADMIN_SECRET=$(new_secret 24)
ORG_PII_KEY=$(new_secret 32)
NATIVE_PII_KEY=$(new_secret 32)
NATIVE_PII_HMAC_KEY=$(new_secret 32)
NATIVE_GIFTCARD_CODE_KEY=$(new_secret 32)
NATIVE_OPERATOR_TOKEN_KEY=$(new_secret 32)
MINIO_ROOT_PASSWORD=$(new_secret 32)
MEDIA_RESTAURANT_SECRET_KEY=$(new_secret 32)
MEDIA_EMPLOYEE_SECRET_KEY=$(new_secret 32)
MEDIA_PAYMENT_SECRET_KEY=$(new_secret 32)
TUNNEL_UUID=
EOF
  umask 022
fi
chmod 600 prod.env

envget() { grep -E "^$1=" prod.env | head -1 | cut -d= -f2-; }
envset() { # envset KEY VALUE — in-place, preserving everything else
  local tmp; tmp=$(mktemp)
  awk -v k="$1" -v v="$2" 'BEGIN{FS=OFS="="} $1==k{$0=k"="v; done=1} {print} END{if(!done) print k"="v}' prod.env > "$tmp"
  cat "$tmp" > prod.env && rm -f "$tmp"
}

profiles=$(envget COMPOSE_PROFILES); export COMPOSE_PROFILES="${profiles:-quicktunnel}"
COMPOSE="docker compose --env-file prod.env -f compose.prod.yml -f $MANIFEST -p native-prod"

# ---- 2. tunnels + URL discovery --------------------------------------------------------------
log "starting edge + quick tunnels"
$COMPOSE up -d edge cloudflared cloudflared-employee

discover() { # discover <metrics-port> — quick-tunnel hostname from cloudflared metrics
  local host="" i
  for i in $(seq 1 30); do
    host=$(curl -fsS -m 3 "http://127.0.0.1:$1/quicktunnel" 2>/dev/null | jq -r '.hostname // empty') && [ -n "$host" ] && break
    sleep 2
  done
  [ -n "$host" ] && echo "https://$host"
}
PUBLIC_URL=$(discover 12001)    || { log "FATAL: business quick-tunnel URL discovery failed"; exit 2; }
EMPLOYEE_URL=$(discover 12002)  || { log "FATAL: employee quick-tunnel URL discovery failed"; exit 2; }
log "public URLs: business=$PUBLIC_URL employee=$EMPLOYEE_URL"

# ---- 3. env rewrite --------------------------------------------------------------------------
[ "$(envget PUBLIC_URL)" = "$PUBLIC_URL" ] || { envset PUBLIC_URL "$PUBLIC_URL"; log "PUBLIC_URL updated — URL-dependent containers will recreate"; }
envset EMPLOYEE_PUBLIC_URL "$EMPLOYEE_URL"

# ---- 4. full stack ---------------------------------------------------------------------------
log "starting the full stack (first boot: Flyway + realm import — be patient)"
if [ "$SKIP_PULL" != "--skip-pull" ]; then $COMPOSE pull -q; fi
$COMPOSE up -d --remove-orphans --wait --wait-timeout 900 || {
  log "FATAL: stack failed to reach healthy — inspect: docker compose -p native-prod ps / logs"
  exit 2
}

# ---- 5. keycloak wiring ----------------------------------------------------------------------
log "patching Keycloak for the current origins"
KCADM="docker exec native-prod-keycloak /opt/keycloak/bin/kcadm.sh"
CFG="--config /tmp/kcadm.config"
$KCADM config credentials --server http://localhost:8080/auth --realm master \
  --user admin --password "$(envget KC_ADMIN_PASSWORD)" $CFG >/dev/null

kc_client_id() { $KCADM get clients -r native -q "clientId=$1" --fields id,clientId $CFG | jq -r ".[] | select(.clientId==\"$1\") | .id"; }

# native-console SPA -> both quick-tunnel origins (GET-modify-PUT so untouched attrs survive).
CID=$(kc_client_id native-console)
[ -n "$CID" ] || { log "FATAL: native-console client not found in realm"; exit 2; }
$KCADM get "clients/$CID" -r native $CFG \
  | jq --arg u "$PUBLIC_URL" --arg e "$EMPLOYEE_URL" \
      '.redirectUris = [$u+"/*", $e+"/*"]
       | .webOrigins  = [$u, $e]
       | .attributes["post.logout.redirect.uris"] = $u+"/*##"+$e+"/*"' > /tmp/native-console-client.json
docker cp /tmp/native-console-client.json native-prod-keycloak:/tmp/native-console-client.json
rm -f /tmp/native-console-client.json
$KCADM update "clients/$CID" -r native -f /tmp/native-console-client.json $CFG

# Rotate the committed native-admin secret to the generated one (org-service uses it).
AID=$(kc_client_id native-admin)
[ -n "$AID" ] && $KCADM update "clients/$AID" -r native -s "secret=$(envget KEYCLOAK_ADMIN_SECRET)" $CFG

# native-gateway: direct-access grants + committed secret = password oracle. Unused — disable.
GID=$(kc_client_id native-gateway)
[ -n "$GID" ] && $KCADM update "clients/$GID" -r native -s enabled=false $CFG

# Committed seed users are weak public credentials — prod is signup-only.
for u in owner-acme cashier-acme; do
  UID_=$($KCADM get users -r native -q "username=$u" --fields id,username $CFG | jq -r ".[] | select(.username==\"$u\") | .id")
  [ -n "$UID_" ] && $KCADM update "users/$UID_" -r native -s enabled=false $CFG
done

# ADR 0054 realm hardening — exact values mirrored from the live UAT realm.
$KCADM update realms/native $CFG \
  -s bruteForceProtected=true -s failureFactor=15 \
  -s waitIncrementSeconds=60 -s maxFailureWaitSeconds=900 \
  -s 'passwordPolicy=length(10) and notUsername(undefined) and notEmail(undefined) and passwordHistory(3)'
log "keycloak wired: origins patched, admin secret rotated, gateway client + seed users disabled, ADR 0054 hardening applied"

# ---- 6. debezium connectors ------------------------------------------------------------------
log "registering Debezium connectors (idempotent PUT)"
for f in debezium/*.json; do
  [ -f "$f" ] || continue
  name=$(jq -r '.name' "$f")
  jq '.config' "$f" | curl -fsS -X PUT -H 'Content-Type: application/json' \
    --data-binary @- "http://127.0.0.1:19093/connectors/$name/config" >/dev/null \
    || { log "FATAL: connector $name registration failed"; exit 2; }
done
for f in debezium/*.json; do
  [ -f "$f" ] || continue
  name=$(jq -r '.name' "$f"); state=""
  for i in $(seq 1 15); do
    sleep 2
    status=$(curl -fsS "http://127.0.0.1:19093/connectors/$name/status" 2>/dev/null) || continue
    state=$(echo "$status" | jq -r '.connector.state')
    # restart transiently-failed tasks and keep polling (raced a postgres restart etc.)
    for tid in $(echo "$status" | jq -r '.tasks[] | select(.state=="FAILED") | .id'); do
      state=TASK_FAILED
      curl -fsS -X POST "http://127.0.0.1:19093/connectors/$name/tasks/$tid/restart" >/dev/null || true
    done
    [ "$state" = "RUNNING" ] && break
  done
  [ "$state" = "RUNNING" ] || log "WARN: connector $name is '$state' (expected RUNNING)"
done

# ---- 7. smoke through the PUBLIC URLs --------------------------------------------------------
log "smoke tests through the public URLs"
fails=0
smoke_check() { # smoke_check <desc> <expected-status-regex> <url>
  local code; code=$(curl -s -o /dev/null -m 15 -w '%{http_code}' "$3")
  if echo "$code" | grep -qE "$2"; then log "  ok: $1 ($code)"; else log "  SMOKE FAIL: $1 (got $code, want $2)"; fails=$((fails+1)); fi
}
envjs=$(curl -fsS -m 15 "$PUBLIC_URL/env.js" 2>/dev/null || true)
echo "$envjs" | grep -q "$PUBLIC_URL/auth" && log "  ok: env.js carries the public KC URL" \
  || { log "  SMOKE FAIL: env.js does not carry $PUBLIC_URL/auth"; fails=$((fails+1)); }
issuer=$(curl -fsS -m 15 "$PUBLIC_URL/auth/realms/native/.well-known/openid-configuration" 2>/dev/null | jq -r '.issuer // empty')
[ "$issuer" = "$PUBLIC_URL/auth/realms/native" ] && log "  ok: OIDC issuer matches" \
  || { log "  SMOKE FAIL: issuer '$issuer' != $PUBLIC_URL/auth/realms/native"; fails=$((fails+1)); }
smoke_check "unauthenticated /api -> 401"      '^401$'        "$PUBLIC_URL/api/v1/companies/mine"
smoke_check "KC admin blackholed -> 404"       '^404$'        "$PUBLIC_URL/auth/admin/"
smoke_check "bogus media key -> 403/404"       '^(403|404)$'  "$PUBLIC_URL/api/media/restaurant/smoke/menu/$(printf '0%.0s' $(seq 64)).jpg"
smoke_check "employee origin serves the SPA"   '^200$'        "$EMPLOYEE_URL/"

if [ "$fails" -gt 0 ]; then log "BOOTSTRAP: $fails smoke check(s) FAILED — stack is up but not verified"; exit 1; fi
cp "$MANIFEST" releases/LAST_GOOD.images.yml; echo "$RELEASE" > LAST_GOOD
log "=== BOOTSTRAP SUCCESS — business: $PUBLIC_URL  employee: $EMPLOYEE_URL (recorded as LAST_GOOD) ==="
log "NOTE: quick-tunnel URLs are EPHEMERAL — if the tunnels restart, re-run this script to re-wire."
