# Native - release-manifest generator (ADR 0057, Phase 2).
#
# Resolves every prod image for a source ref to its IMMUTABLE @sha256 digest and writes a
# digest-pinned compose override (docker/compose.prod.images.yml). Tags are mutable; digests
# are not - deploying/rolling-back by digest is what guarantees "what passed QA is what ships"
# (ADR 0053 section 1). Phase 4's deploy-prod uses the override; rollback re-applies a prior one.
#
#   ./scripts/release-manifest.ps1 -Tag <git-sha-or-version>   # what images.yml tagged
#   docker compose -f docker/compose.prod.yml -f docker/compose.prod.images.yml -p native-prod ...
#
# Requires: docker (buildx) logged in to GHCR with read:packages
#   echo $env:GHCR_TOKEN | docker login ghcr.io -u <github-user> --password-stdin
#
# FAILS LOUDLY if any image is missing at that ref - an incomplete image set must never
# deploy (this is exactly how the old payment-service/employee-web gap would have surfaced).

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$Tag,
    [string]$ImageBase = 'ghcr.io/rfkih/native-monorepo',
    [string]$OutFile = (Join-Path (Split-Path -Parent $PSScriptRoot) 'docker\compose.prod.images.yml')
)

$ErrorActionPreference = 'Stop'

# compose-service-name -> GHCR image repo. Backend service names match their image; the two
# SPAs are published as *-web. Keep in sync with compose.prod.yml + images.yml.
$map = [ordered]@{
    'gateway'              = 'gateway'
    'org-service'          = 'org-service'
    'restaurant-service'   = 'restaurant-service'
    'carwash-service'      = 'carwash-service'
    'barbershop-service'   = 'barbershop-service'
    'loyalty-service'      = 'loyalty-service'
    'finance-service'      = 'finance-service'
    'entitlement-service'  = 'entitlement-service'
    'employee-service'     = 'employee-service'
    'notification-service' = 'notification-service'
    'payment-service'      = 'payment-service'
    'console'              = 'console-web'
    'employee'             = 'employee-web'
}

function Resolve-Digest {
    param([string]$Repo)
    $ref = "${ImageBase}/${Repo}:${Tag}"
    # --format '{{.Manifest.Digest}}' prints the immutable index/manifest digest.
    $digest = (& docker buildx imagetools inspect $ref --format '{{.Manifest.Digest}}' 2>$null)
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($digest)) {
        throw "Cannot resolve $ref. Is the image built at this ref and are you logged in to GHCR? An incomplete image set must not deploy."
    }
    return $digest.Trim()
}

Write-Host "Resolving $($map.Count) image digests for '$Tag' from $ImageBase ..." -ForegroundColor Cyan

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# GENERATED by scripts/release-manifest.ps1 - DO NOT EDIT.")
$lines.Add("# Pins every native-prod image to an immutable @sha256 digest for release: $Tag")
$lines.Add("# Source tag: $Tag   Registry: $ImageBase")
$lines.Add("# Deploy: docker compose -f docker/compose.prod.yml -f docker/compose.prod.images.yml -p native-prod up -d")
$lines.Add("name: native-prod")
$lines.Add("services:")

foreach ($svc in $map.Keys) {
    $digest = Resolve-Digest -Repo $map[$svc]
    $pinned = "${ImageBase}/$($map[$svc])@${digest}"
    Write-Host ("  {0,-22} {1}" -f $svc, $digest) -ForegroundColor DarkGray
    $lines.Add("  ${svc}:")
    $lines.Add("    image: $pinned")
}

Set-Content -Path $OutFile -Value $lines -Encoding utf8
Write-Host "Wrote digest-pinned override -> $OutFile" -ForegroundColor Green
